### PR TITLE
add XP param

### PR DESCRIPTION
**Pull request by ett126**
XPのコインパラメータを追加しました。

### CODE REVIEW

**Comment by MissMonacoin** [comment]
I ｍerged but coin addition doesn't work due to new features.
This must have contained new fields.
I'll fix this problem after I get back to home.
So, I have a question for this.
Do XP Coin supports non-standard transaction, including OP_RETURN?

**Comment by ett126** [comment]
XP is a fork coin of bitcoin v0.6, probably not supporting non-standard transactions.
I will investigate in detail as I return home.

If you do not support it, do I need a coin based update?

**Comment by MissMonacoin** [comment]
What does it mean "coin based update" ?

**Comment by ett126** [comment]
sorry.It means update of XPCoin core.

**Comment by ett126** [comment]
Sorry for my late reply
I saw the source code of XPCoin core.
OP_RETURN seems to support as standard transaction.

**Comment by MissMonacoin** [comment]
How long is maximum message?

**Comment by MissMonacoin** [comment]
Ok. I will enable messaging up to 80 byte

**Comment by ett126** [comment]
Thank you
If there is something please contact me.
also, provide XP for testing.

**Comment by MissMonacoin** [comment]
https://monya-wallet.github.io/addcoins/
Coin param is available here now.

**Comment by ett126** [comment]
understood. I will start the test.

**Comment by ett126** [comment]
XPCoin Receive,Sign message,Verify signed message succeeded.
but,I fail with remittance.
It looks like it can not decode a signed transaction.


```
#decoderawtransaction 010000000190b927fae72ab0e92512df887dc0e829debc1b25f46af4c26f78a9da6941c842010000006a4730440220734aac32567ea3c8f2ee5d445ebaedd99d590f3f55681766be83faea79cca52202207d7117432960a5f4e9aa18c64aa4fffba3e9be0666e809112d43ce8ee5a549e80121034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0280f0fa02000000001976a914899402642ecc722bfb1818f72edae1f36d68aeaf88aca6c0fa02000000001976a91483747e645939d4d6d82c945776b484715640859f88ac00000000
error: {"code":-22,"message":"TX decode failed"}
```

```
#decodescript 010000000190b927fae72ab0e92512df887dc0e829debc1b25f46af4c26f78a9da6941c842010000006a4730440220734aac32567ea3c8f2ee5d445ebaedd99d590f3f55681766be83faea79cca52202207d7117432960a5f4e9aa18c64aa4fffba3e9be0666e809112d43ce8ee5a549e80121034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0280f0fa02000000001976a914899402642ecc722bfb1818f72edae1f36d68aeaf88aca6c0fa02000000001976a91483747e645939d4d6d82c945776b484715640859f88ac00000000
{
    "asm" : "0 0 0 -16 OP_NOP10 fae72ab0e92512df887dc0e829debc1b25f46af4c26f78a9da6941c842010000006a4730440220 OP_IFDUP ac32567ea3c8f2ee5d445ebaedd99d590f3f55681766be83faea79cca52202207d7117432960a5f4e9aa18c64aa4fffba3e9be0666e809112d43ce8ee5a549e80121034bc9e26e9c65da eb604f369946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0280f0fa02000000001976a914899402642ecc722bfb1818f72edae1f36d68aeaf88aca6c0fa02000000 0 76a91483747e645939d4d6d82c945776b484715640859f88ac 0 0 0 0",
    "type" : "nonstandard",
    "p2sh" : "9AvKro95yVvL6iuoMieX5oWDDBayKzpvMb"
}
```
After all, it seems that it can not support nonstandard transactions.

**Comment by MissMonacoin** [comment]
change library into blackcoinjs-lib
See NEET params.

**Comment by ett126** [comment]
Thank you very much. I changed the library.
It is now possible to decode, but it will be rejected as a lack of fee.

It seems that the remittance amount entered has changed.

I entered as follows
(Balance:99.99999XP)
Send:20XP
Fee:0.0001125XP

The output transactions are as follows
vout0:2000
vout1:7999.98775

I do not know why, but it will be 100x.

```
decoderawtransaction 010000005267e45a01ffd89f07154056a2da8473958f83c38fb5a825af05d56b61a1a28c08429b3612010000006a473044022034ab4284a84edcce16a4309c337c3f0370837aa5ea00594a77d60ccac5cc67e802206267590269a46e07897c760ae709c38fc86171f2985fdcf56f6be0f32bb44aa40121034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0200943577000000001976a914899402642ecc722bfb1818f72edae1f36d68aeaf88ac2620d6dc010000001976a91483747e645939d4d6d82c945776b484715640859f88ac00000000
{
    "txid" : "23be6c93519eded315d68667d295787161714aa176c882f7505a5217adecb7d7",
    "version" : 1,
    "time" : 1524918098,
    "locktime" : 0,
    "vin" : [
        {
            "txid" : "12369b42088ca2a1616bd505af25a8b58fc3838f957384daa2564015079fd8ff",
            "vout" : 1,
            "scriptSig" : {
                "asm" : "3044022034ab4284a84edcce16a4309c337c3f0370837aa5ea00594a77d60ccac5cc67e802206267590269a46e07897c760ae709c38fc86171f2985fdcf56f6be0f32bb44aa401 034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60c",
                "hex" : "473044022034ab4284a84edcce16a4309c337c3f0370837aa5ea00594a77d60ccac5cc67e802206267590269a46e07897c760ae709c38fc86171f2985fdcf56f6be0f32bb44aa40121034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60c"
            },
            "sequence" : 4294967295
        }
    ],
    "vout" : [
        {
            "value" : 2000.00000000,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 899402642ecc722bfb1818f72edae1f36d68aeaf OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914899402642ecc722bfb1818f72edae1f36d68aeaf88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "XPtgjJ4UhZtoMFsKsJSEW7J775wePzRCxc"
                ]
            }
        },
        {
            "value" : 7999.98775000,
            "n" : 1,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 83747e645939d4d6d82c945776b484715640859f OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a91483747e645939d4d6d82c945776b484715640859f88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "XPLJvQAJTpYp9YoWk9EwLLVcxpMX2Vg34U"
                ]
            }
        }
    ]
}
```
```
decodescript 010000005267e45a01ffd89f07154056a2da8473958f83c38fb5a825af05d56b61a1a28c08429b3612010000006a473044022034ab4284a84edcce16a4309c337c3f0370837aa5ea00594a77d60ccac5cc67e802206267590269a46e07897c760ae709c38fc86171f2985fdcf56f6be0f32bb44aa40121034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0200943577000000001976a914899402642ecc722bfb1818f72edae1f36d68aeaf88ac2620d6dc010000001976a91483747e645939d4d6d82c945776b484715640859f88ac00000000
{
    "asm" : "0 0 0 2 OP_ELSE OP_UNKNOWN 10 -127 OP_UNKNOWN OP_LESSTHAN 154056a2da8473 OP_MUL OP_NEGATE OP_INVERT OP_UNKNOWN OP_NEGATE OP_NOP6 OP_SHA256 af05d56b61a1a28c08429b3612010000006a473044022034ab4284a84edcce16a4309c337c 0370837aa5ea00594a77d60ccac5cc67e802206267590269a46e07897c760ae709c38fc86171f2985fdcf56f6be0f32bb44aa40121034bc9e26e9c65da46eb 16 -1 9946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0200943577000000001976a914899402642ecc722bfb1818f72edae1f36d OP_ENDIF OP_CHECKMULTISIG OP_CHECKMULTISIGVERIFY OP_EQUALVERIFY OP_CHECKSIG [error]",
    "type" : "nonstandard",
    "p2sh" : "9DkLLH1LMiRi2nZzB3C6dNJhVSA1eut3X9"
}
```
```
sendrawtransaction 010000005267e45a01ffd89f07154056a2da8473958f83c38fb5a825af05d56b61a1a28c08429b3612010000006a473044022034ab4284a84edcce16a4309c337c3f0370837aa5ea00594a77d60ccac5cc67e802206267590269a46e07897c760ae709c38fc86171f2985fdcf56f6be0f32bb44aa40121034bc9e26e9c65da46eb604f369946d8971743cfdaf27c60ccf6cb11450679d60cffffffff0200943577000000001976a914899402642ecc722bfb1818f72edae1f36d68aeaf88ac2620d6dc010000001976a91483747e645939d4d6d82c945776b484715640859f88ac00000000
error: {"code":-22,"message":"TX rejected"}
```
coin deamon error log:
```
ERROR: CTxMemPool::accept() : not enough fees 23be6c93519eded315d68667d295787161714aa176c882f7505a5217adecb7d7, -9899987760 < 0
```
Sorry to bother you again.
I will continue to investigate.

**Comment by MissMonacoin** [comment]
Somehow XP needs incredibly high fee.
CryptoBridge also needed 460 XP for fee.
I read source but I can't find the reason.

**Comment by ett126** [comment]
Certainly the CryptoBridge fee is high.

I do not know the cause yet.
Please let me stop the addition of XPcoins.

**Pull request merged**
