### PR TITLE
Change GNU GPL v3 into MIT License

### PR DESCRIPTION
**Pull request by MissMonacoin**
We're going to change software license in order for the zenypota team to use source code of monya and for everyone to develop or compile freely.
For contributors who've ever made a pull request: if you are not agree with the license replacement, you have a right to claim.

### CODE REVIEW

**Comment by fujiwaraizuho** [comment]
Margeしちゃっていい？

**Comment by MissMonacoin** [comment]
まだ待って。1~2週間ほど置いて異議を唱えることにしたい。

**Comment by lae** [comment]
良いと思う。

**Comment by MissMonacoin** [comment]
依存関係のライセンスは解決
https://gist.github.com/MissMonacoin/e660ba2d7ffd40837e03899ddfcb7327

**Comment by fujiwaraizuho** [comment]
ってことはあとは承認待ちか…

**Pull request merged**
