### PR TITLE
Fix segwit signature bug

### PR DESCRIPTION
**Pull request by MissMonacoin**
Fix signing message with P2SH-P2WPKH address.
With this, Bitcoin(Segwit) signature can be signed & verified correctly.

### CODE REVIEW

**Comment by junderw** [comment]
Why are you removing password strength checks?

**Comment by MissMonacoin** [comment]
Oh, I forgot to revert the strength check when I was debugging.
I fix it all. Thank you for reviewing!

**Comment by fujiwaraizuho** [comment]
https://github.com/monya-wallet/monya/blob/4e5e8e57da648a3380e49b797ee79ddd44406015/js/currency.js#L650-L658

Are you branching the same process?

**Comment by junderw** [comment]
> https://github.com/monya-wallet/monya/blob/4e5e8e57da648a3380e49b797ee79ddd44406015/js/currency.js#L650-L658
> 
> Are you branching the same process?

They removed this part in 9f4d334

**Comment by fujiwaraizuho** [comment]
@junderw thanks!

**Pull request merged**
